CC	:= ${CXX}

SRCS_CXX:= main.cpp bwtree.cpp
TARGET  := bwtree
TREE	:= -DBWTREE
EXTRAC  := -fpermissive -pthread -std=c++11 -mcx16 -Wno-invalid-offsetof
EXTRAL  := -latomic

include  ../common/common.mk
